version: '3.8'
services:
  app:
    build: ./
    container_name: "finance_service_app"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    networks:
      - finance_service

  db:
    image: mysql:8.0
    container_name: "finance_service_db"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}   
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - ./.env
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - finance_service

networks:
  finance_service:
    driver: bridge